### ISSUE TITLE
First pass at a Kythe indexer for the Scala Language. [phab:D924]

### ISSUE THREAD

**Issue by kythe** [google/kythe#1239]
_Created by **fromberger** at 2016-06-11 20:58:39_: 

Note: No instructions on running yet because it is still difficult to
self-host this with bazel.  The scala actions are skylark based, not internal
so we just get a SpawnAction that we have to parse arguments from.
It actually works if you specify it in the plugins attribute on scala_library rule, but it has no
where to write its output and it is obviously the wrong way to add a
plugin.

**Comment by kythe** [comment]
_**rbraunstein** wrote at 2016-06-13 17:15:06_:

  - added path fixup code

**Comment by kythe** [comment]
_**shahms** commented inline (context lost during migration) at 2016-06-14 16:23:41_:

This is likely related to the --legacy_external_runfiles change.  Can you try this with 0.3.0 after a `bazel clean --expunge`?

**Comment by kythe** [comment]
_**shahms** commented inline (context lost during migration) at 2016-06-14 16:23:41_:

left over comment?

**Comment by kythe** [comment]
_**shahms** commented inline (context lost during migration) at 2016-06-14 16:23:41_:

Can you put this in a `sh_binary()` and depend on it as a tool?  Arguably, you should depend on the configured `jar` binary as well, rather than system one.

**Comment by kythe** [comment]
_**shahms** commented inline (context lost during migration) at 2016-06-14 16:23:41_:

nit: please fix

**Comment by kythe** [comment]
_**shahms** wrote at 2016-06-14 16:23:41_:

I don't know Scala, so limiting myself to BUILD, etc.

**Comment by kythe** [comment]
_**rbraunstein** wrote at 2016-06-14 20:32:18_:

  - Moved rejaring code to sh_binary

**Comment by kythe** [comment]
_**rbraunstein** wrote at 2016-06-14 20:33:52_:

I think I lost my local commit message to arc, here it is:


 Moved rejaring code to sh_binary
    
    The right longterm fix is to fixup the scala.bzl rules to put the xml
    file in the right place.
    
    Getting right version of jar is harder than it should be.
    Adding deps to sh_binary says it doesn't accept filegroups, but it also
    says the dep should be a filegroup.  Adding it as data puts in in the
    runfiles directory, so we add it to the genrule that calls sh_binary for
    now.
    
    Removed comments for scala_binary rule since I'm not trying to make one
    any more.  Renamed MyMain to something better in the process.

**Comment by kythe** [comment]
_**shahms** commented inline (context lost during migration) at 2016-06-14 20:42:51_:

All shell dependencies are "runfiles"

**Comment by kythe** [comment]
_**shahms** commented inline (context lost during migration) at 2016-06-14 20:42:51_:

can you enquote the various $shell variables which represent paths?

**Comment by kythe** [comment]
_**shahms** wrote at 2016-06-14 20:42:51_:

Minor issues aside, the BUILD/shell seems fine to me.

**Comment by kythe** [comment]
_**rbraunstein** wrote at 2016-06-14 20:53:35_:

  - Fix shell script to use ${foo} instead of $foo

**Comment by kythe** [comment]
_**schroederc** wrote at 2016-07-19 15:58:31_:

This change should be rebased.  It fails at HEAD.

**Comment by kythe** [comment]
_**schroederc** required changes at 2016-07-19 15:58:31_

**Comment by kythe** [comment]
_**rbraunstein** wrote at 2016-07-19 19:18:47_:

  - Fix shell script to use ${foo} instead of $foo

**Comment by kythe** [comment]
_**shahms** commented inline (context lost during migration) at 2016-07-22 18:19:07_:

This path is going to depend on --legacy_external_runfiles; I would make this a template that is generated with the correct path.

**Comment by kythe** [comment]
_**shahms** commented inline (context lost during migration) at 2016-07-22 18:19:07_:

enquote the variable reference; arguably also include an error if this is unset:

finaljar="${1:?Missing required output path}"

**Comment by kythe** [comment]
_**shahms** commented inline (context lost during migration) at 2016-07-22 18:19:07_:

Prefer `mktemp -d`

**Comment by kythe** [comment]
_**jrtom** wrote at 2017-10-18 16:45:34_:

Going through old open Phabricator tasks: does anyone on the Grok team have both the time and expertise to review this submission further, or should we archive this?  (I don't know Scala, and I'm not sure who does.)

What's our minimum bar for letting this be submitted?

**Comment by kythe** [comment]
_**fromberger** wrote at 2017-10-18 17:13:24_:

>>! In (earlier comment), jrtom wrote:
> Going through old open Phabricator tasks: does anyone on the Grok team have both the time and expertise to review this submission further, or should we archive this?  (I don't know Scala, and I'm not sure who does.)
> 
> What's our minimum bar for letting this be submitted?

We'll need someone with enough Scala expertise to evaluate whether it makes sense, and of course make sure it works.

We'll also need to sort out the build system integration. The Scala compiler gets almost all its configuration from implicit context, which makes it tricky for Bazel.

So: Someone will need to think it's important enough to work on it, and solve those two problems. :)

**Comment by kythe** [comment]
_**fromberger** wrote at 2018-05-21 20:24:39_:

As part of the move off Phabricator to GitHub pull requests, I'm abandoning this revision. If someone wants to pursue it further, please start a new issue on https://github.com/google/kythe/issues.

**Comment by kythe** [comment]
_**fromberger** abandoned revision at 2018-05-21 20:24:39_

**Comment by ronstripe** [comment]
Hey, is there any chance of resurrecting the scala indexer branch from phabricator? Or do you know of any kythe scala indexers?

-ron

**Comment by shahms** [comment]
As this was never submitted, I think it was lost in the migration.  I don't know how one would go about reviving it.
