### ISSUE TITLE
FYI Basic test failure [phab:T253]

### ISSUE THREAD

**Issue by kythe** [google/kythe#2135]
_Created by **djrenren** at 2017-06-12 21:16:39_: 

//kythe/cxx/tools/fyi/testdata:basic                                     FAILED

```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
-----------------------------------------------------------------------------
2017/06/12 21:13:01 Starting serving pipeline
2017/06/12 21:13:01 Writing partial edges
2017/06/12 21:13:01 Writing complete edges
2017/06/12 21:13:01 Writing EdgeSets
2017/06/12 21:13:01 Writing decoration fragments
2017/06/12 21:13:01 Writing completed FileDecorations
2017/06/12 21:13:01 Writing CrossReferences
2017/06/12 21:13:03 xrefs.Edges:	212.359µs
2017/06/12 21:13:03 xrefs.Edges:	36.532904ms
2017/06/12 21:13:03 xrefs.Edges:	39.718332ms
fyi: malloc.c:4157: malloc_consolidate: Assertion `p->fd_nextsize->bk_nextsize == p' failed.
./kythe/cxx/tools/fyi/testdata/test_case.sh: line 43:    48 Aborted                 (core dumped) "${FYI}" --xrefs="${XREFS_URI}" "${TEST_FILE}" > "${TEST_FILE}.actual"
Expected zero return from tool, saw 134
0a1,8
> #include <stdio.h>
> #include "basic.h"
> 
> 
> int main() {
>   foo();
>   return 0;
> }
Use --strategy=TestRunner=standalone to disable sandboxing for the failing actions.
````

**Comment by kythe** [comment]
_**shahms** wrote at 2017-06-12 21:19:07_:

Which version of clang are you using?

**Comment by kythe** [comment]
_**djrenren** wrote at 2017-06-12 21:29:44_:

3.5

```
% clang --version
Ubuntu clang version 3.5.0-4ubuntu2~trusty2 (tags/RELEASE_350/final) (based on LLVM 3.5.0)
Target: x86_64-pc-linux-gnu
Thread model: posix
```

**Comment by kythe** [comment]
_**shahms** wrote at 2017-06-12 21:35:51_:

Hrm, that doesn't appear to be the culprit (I couldn't reproduce using clang-3.5). You're using bazel 0.5.1 and a checkout of Kythe from HEAD?
What does `third_pary/llvm/llvm/build` link to?

**Comment by kythe** [comment]
_**djrenren** wrote at 2017-06-13 19:27:02_:

Yup 0.5.1 and HEAD (commit 84662ccbc4a60745be28e5d15218ba6b5dead12d)

links to `third_party/llvm/llvm/build.9502e5be6f671ec0d6f24e8586cc20faa77fbbcb.b19f8fa7328ea6963987cc52ecf46cde361cb181`

**Comment by kythe** [comment]
_**zarko** wrote at 2017-06-13 19:30:50_:

Ran the test under valgrind and confirmed that it's a bug. Likely clang is doing something unexpected with reparsed buffers.

**Comment by creachadair** [comment]
I am not able to reproduce this any longer.
