### ISSUE TITLE
Kythe doesn't handle conditional bindings with different types [phab:T272]

### ISSUE THREAD

**Issue by kythe** [google/kythe#2381]
_Created by **pludemann** at 2017-09-19 01:20:55_: 

The following Python code snippet should produce both a `function` and a `record` (subkind `class`) for the two `defines/binding`s of `popen`. But Kythe verifier complains that "Two facts about a node differed in value".

(This code comes from https://github.com/python/typeshed/blob/master/stdlib/2/os/__init__.pyi#L270)

```
if sys.version_info >= (3, 0):
    class popen(_TextIOWrapper):
        # TODO 'b' modes or bytes command not accepted?
        def __init__(self, command: str, mode: str = ...,
                     bufsize: int = ...) -> None: ...
        def close(self) -> Any: ...  # may return int
else:
    def popen(command: str, *args, **kwargs) -> Optional[IO[Any]]: ...
    def popen2(cmd: str, *args, **kwargs) -> Tuple[IO[Any], IO[Any]]: ...
    def popen3(cmd: str, *args, **kwargs) -> Tuple[IO[Any], IO[Any], IO[Any]]: ...
    def popen4(cmd: str, *args, **kwargs) -> Tuple[IO[Any], IO[Any]]: ...
```

**Comment by kythe** [comment]
_**fromberger** wrote at 2017-09-19 02:58:15_:

Facts are intentionally single-valued and the data model assumes that equal tickets have equal facts. That's not something we plan to change.

I would probably model these as distinct nodes, with different vnames. Usage sites where it's statically known which type they're calling can point to the correct one.  For other cases, some workable alternatives might include:

* Interpose a `lookup` node for cases where no static choice is practical.
* Since `sys.version_info` is "essentially static", special case it in top-level conditionals (this is a pretty common case).
* Treat both definitions as instantiations of an `abs` node whose `param.0` is (as appropriate) a `function` or `record`.

There are probably others. Intuitively I'd lean toward a model that allows the cross-references for the definitions to be distinguished from each other. Based on user reports in similar cases from other languages, I'd predict users who visit the `popen` anchor in the `else:` clause will want to see only the uses of that //particular// definition rather than the class form. But that's only a guess at this point.

**Comment by kythe** [comment]
_**pludemann** wrote at 2017-09-19 03:58:11_:

The problem comes from trying to fit Python's dynamic model (everything is a `variable`) to Kythe's more static model (there are `variable`s, `record`s, `function`s). A simple Python type analyzer would conclude that `popen` is a union of class and function — a more sophisticated analysis such as SSA and if-splitting is, of course, possible; but adds complexity in order to handle some not very common corner cases.

The more natural way of modeling this in Python is to leave `popen` as a `variable` and then add a `typed` edge to Union[class,function] (or `typed` edges to class and function — the documentation isn't clear which is preferred). But if I did this everywhere, it would probably confuse tools that expect the kinds of facts that C++ or Java generate.

To help me understand the issues, could you please show what kind of facts would be output for a `lookup` or `abs` (or `typed`, if that makes sense)? The schema doc examples are rather far from a "union type".

BTW, the "conditional" part of task title is misleading ... this is perfectly valid Python (although perhaps not very meaningful):
```
class popen(_TextIOWrapper):
   def __init__(self, command: str, mode: str = ..., bufsize: int = ...) -> None: ...
popen_py3 = popen
def popen(command: str, *args, **kwargs) -> Optional[IO[Any]]: ...
popen_py2 = popen
```

**Comment by kythe** [comment]
_**pludemann** wrote at 2017-09-20 03:48:27_:

If the source is analyzed in isolation, there's no way of knowing what value of `sys.version_info` will have, so if-splitting can't be done, nor can the value be considered "essentially static".

I've got a work-around: if there are multiple types, I default to `variable`. However, it'd be nice to have a recommended way of handling such situations of "union" types (i.e., a `lookup` or `abs`), so that tools that use Kythe know what to expect.

**Comment by creachadair** [comment]
I don't think there is anything actionable here; the data model and the schema allow treating cases like this as separate nodes, and that ought be sufficient to handle cases like these where there are variant definitions.
