### ISSUE TITLE
Add subkinds to `doc` nodes [phab:T290]

### ISSUE THREAD

**Issue by kythe** [google/kythe#2677]
_Created by **schroederc** at 2018-03-07 23:04:46_: 

Differentiate between standard documentation (e.g. JavaDoc) versus other commenting (e.g. `//` line comments).

**Comment by schroederc** [comment]
Fixed by 72169bc0c2025e6e5a2e12f81de7e5d4a1981f19

**Comment by kythe** [comment]
revision #2680
