### ISSUE TITLE
C++ compilation of rule '//kythe/cxx/common:k\ zip_writer_test' failed

### ISSUE THREAD

**Issue by kamahen** [google/kythe#2874]
```
kythe/cxx/common/kzip_writer_test.cc:89:5: error: return type 'kythe::Status' must match previous return\
 type 'const kythe::Status' when lambda expression has unspecified explicit return type
    return OkStatus();
    ^
kythe/cxx/common/kzip_writer_test.cc:112:5: error: return type 'kythe::Status' must match previous retur\
n type 'const kythe::Status' when lambda expression has unspecified explicit return type
    return OkStatus();
    ^
```

Fixed by:   
```
--- a/kythe/cxx/common/status.h
+++ b/kythe/cxx/common/status.h
@@ -87,7 +87,7 @@ class ABSL_MUST_USE_RESULT Status final {
 };

 /// \brief Returns a non-error status.
-inline Status OkStatus() { return {}; }
+inline const Status OkStatus() { return {}; }

 /// \brief Return a Cancelled error with the given message.
 Status CancelledError(absl::string_view message);
```

**Comment by creachadair** [comment]
Thanks, this is #2873. Can you tell me a bit more about your setup? I haven't been able to repro it locally yet.

**Comment by creachadair** [comment]
In particular, can you tell us what `clang --version` you are using?

**Comment by zrlk** [comment]
I can repro with 3.5.2. This may be a bug in clang that's since been fixed.

**Comment by creachadair** [comment]
#2877 should hopefully give you a working build again.

**Comment by shahms** [comment]
This is a compiler bug which we should fix by requiring a compiler without the bug.

**Comment by shahms** [comment]
Yes, at least 3.6. 3.5 is ancient. 3.6 is also pretty old, but is still a better choice.  3.8 and 4.0 should both be broadly available for distros as well.

**Comment by creachadair** [comment]
> Should I install clang-3.6?

I don't know if this particular issue is fixed there. I'm using 4.0.1, and would probably advise using at least 4. To your point, though, we should probably update the documentation to stipulate a higher version.

**Comment by shahms** [comment]
3.8 will work, but Ubuntu has a variety of clang's available including 4.0 (but it's the `clang-4.0` package, rather than just `clang`).  You'll likely also have to set the `CLANG` environment variable to the path to the clang binary so the Bazel repository rules will pick the right version.

**Comment by kamahen** [comment]
3.8 didn't work (on regular Ubuntu 16.04). I'll install clang-4.0 later
today or tomorrow and try again.

ERROR: $HOME/src/kythe/kythe/cxx/indexer/cxx/BUILD:367:1: Linking of rule
'//kythe/cxx/indexer/cxx:indexer' failed (Exit 1)
bazel-out/host/bin/kythe/cxx/indexer/cxx/_objs/imputed_constructor_library_support/kythe/cxx/indexer/cxx/ImputedConstructorSupport.o:kythe/cxx/indexer/cxx/ImputedConstructorSupport.cc:function
kythe::ImputedConstructorSupport::InspectCallExpr(kythe::IndexerASTVisitor&,
clang::CallExpr const*, kythe::GraphObserver::Range const&,
kythe::GraphObserver::NodeId&): error: undefined reference to
'clang::NamedDecl::getQualifiedNameAsString[abi:cxx11]() const'
bazel-out/host/bin/kythe/cxx/indexer/cxx/_objs/indexer_pp_callbacks/kythe/cxx/indexer/cxx/IndexerPPCallbacks.o:kythe/cxx/indexer/cxx/IndexerPPCallbacks.cc:function
kythe::IndexerPPCallbacks::BuildNodeIdForMacro(clang::Token const&,
clang::MacroInfo const&): error: undefined reference to
'clang::SourceLocation::printToString[abi:cxx11](clang::SourceManager
const&) const'
bazel-out/host/bin/kythe/cxx/indexer/cxx/_objs/kythe_graph_observer/kythe/cxx/indexer/cxx/KytheGraphObserver.o:kythe/cxx/indexer/cxx/KytheGraphObserver.cc:function
kythe::KytheGraphObserver::recordIntegerConstantNode(kythe::GraphObserver::NodeId
const&, llvm::APSInt const&): error: undefined reference to
'llvm::APInt::toString[abi:cxx11](unsigned int, bool) const'
bazel-out/host/bin/kythe/cxx/indexer/cxx/_objs/proto_library_support/kythe/cxx/indexer/cxx/ProtoLibrarySupport.o:kythe/cxx/indexer/cxx/ProtoLibrarySupport.cc:function
kythe::GoogleProtoLibrarySupport::InspectCallExpr(kythe::IndexerASTVisitor&,
clang::CallExpr const*, kythe::GraphObserver::Range const&,
kythe::GraphObserver::NodeId&): error: undefined reference to
'clang::QualType::getAsString[abi:cxx11]() const'
bazel-out/host/bin/kythe/cxx/indexer/cxx/_objs/indexer_ast_hooks/kythe/cxx/indexer/cxx/IndexerASTHooks.o:kythe/cxx/indexer/cxx/IndexerASTHooks.cc:function
kythe::IndexerASTVisitor::RangeForNameOfDeclaration(clang::NamedDecl
const*) const: error: undefined reference to
'clang::DeclarationName::getAsString[abi:cxx11]() const'
bazel-out/host/bin/kythe/cxx/indexer/cxx/_objs/indexer_ast_hooks/kythe/cxx/indexer/cxx/IndexerASTHooks.o:kythe/cxx/indexer/cxx/IndexerASTHooks.cc:function
kythe::IndexerASTVisitor::BuildNodeIdForExpr(clang::Expr const*,
kythe::IndexerASTVisitor::EmitRanges): error: undefined reference to
'clang::APValue::getAsString[abi:cxx11](clang::ASTContext&,
clang::QualType) const'
bazel-out/host/bin/kythe/cxx/indexer/cxx/_objs/indexer_ast_hooks/kythe/cxx/indexer/cxx/IndexerASTHooks.o:kythe/cxx/indexer/cxx/IndexerASTHooks.cc:function
kythe::IndexerASTVisitor::BuildNodeIdForTemplateArgument(clang::TemplateArgumentLoc
const&, kythe::IndexerASTVisitor::EmitRanges): error: undefined reference
to 'llvm::APInt::toString[abi:cxx11](unsigned int, bool) const'
bazel-out/host/bin/kythe/cxx/indexer/cxx/_objs/indexer_ast_hooks/kythe/cxx/indexer/cxx/IndexerASTHooks.o:kythe/cxx/indexer/cxx/IndexerASTHooks.cc:function
kythe::IndexerASTVisitor::BuildNodeIdForTemplateArgument(clang::TemplateArgument
const&, clang::SourceLocation): error: undefined reference to
'llvm::APInt::toString[abi:cxx11](unsigned int, bool) const'
bazel-out/host/bin/kythe/cxx/indexer/cxx/_objs/indexer_ast_hooks/kythe/cxx/indexer/cxx/IndexerASTHooks.o:kythe/cxx/indexer/cxx/IndexerASTHooks.cc:function
kythe::IndexerASTVisitor::RecordObjCInterfaceType(kythe::GraphObserver::NodeId,
bool, clang::ObjCObjectType const*, llvm::ArrayRef<clang::SourceLocation>):
error: undefined reference to
'clang::DeclarationName::getAsString[abi:cxx11]() const'
bazel-out/host/bin/kythe/cxx/indexer/cxx/_objs/marked_source/kythe/cxx/indexer/cxx/marked_source.o:kythe/cxx/indexer/cxx/marked_source.cc:function
kythe::GetDeclName[abi:cxx11](clang::LangOptions const&, clang::NamedDecl
const*): error: undefined reference to
'clang::Selector::getAsString[abi:cxx11]() const'
bazel-out/host/bin/kythe/cxx/indexer/cxx/_objs/marked_source/kythe/cxx/indexer/cxx/marked_source.o:kythe/cxx/indexer/cxx/marked_source.cc:function
kythe::MarkedSourceGenerator::GenerateMarkedSourceUsingSource(kythe::GraphObserver::NodeId
const&): error: undefined reference to
'clang::NamedDecl::getQualifiedNameAsString[abi:cxx11]() const'
bazel-out/host/bin/kythe/cxx/indexer/cxx/_objs/marked_source/kythe/cxx/indexer/cxx/marked_source.o:kythe/cxx/indexer/cxx/marked_source.cc:function
kythe::MarkedSourceGenerator::GenerateMarkedSourceUsingSource(kythe::GraphObserver::NodeId
const&): error: undefined reference to
'clang::SourceLocation::printToString[abi:cxx11](clang::SourceManager
const&) const'
bazel-out/host/bin/kythe/cxx/indexer/cxx/_objs/marked_source/kythe/cxx/indexer/cxx/marked_source.o:kythe/cxx/indexer/cxx/marked_source.cc:function
kythe::MarkedSourceGenerator::GenerateMarkedSourceUsingSource(kythe::GraphObserver::NodeId
const&): error: undefined reference to
'clang::SourceLocation::printToString[abi:cxx11](clang::SourceManager
const&) const'
bazel-out/host/bin/kythe/cxx/indexer/cxx/_objs/marked_source/kythe/cxx/indexer/cxx/marked_source.o:kythe/cxx/indexer/cxx/marked_source.cc:function
kythe::MarkedSourceGenerator::GenerateMarkedSourceUsingSource(kythe::GraphObserver::NodeId
const&): error: undefined reference to
'clang::SourceLocation::printToString[abi:cxx11](clang::SourceManager
const&) const'
bazel-out/host/bin/kythe/cxx/indexer/cxx/_objs/marked_source/kythe/cxx/indexer/cxx/marked_source.o:kythe/cxx/indexer/cxx/marked_source.cc:function
kythe::MarkedSourceGenerator::GenerateMarkedSourceUsingSource(kythe::GraphObserver::NodeId
const&): error: undefined reference to
'clang::NamedDecl::getQualifiedNameAsString[abi:cxx11]() const'
bazel-out/host/bin/kythe/cxx/indexer/cxx/_objs/marked_source/kythe/cxx/indexer/cxx/marked_source.o:kythe/cxx/indexer/cxx/marked_source.cc:function
kythe::(anonymous namespace)::DeclAnnotator::Annotate(clang::NamedDecl
const*): error: undefined reference to
'clang::DeclarationName::getAsString[abi:cxx11]() const'
bazel-out/host/bin/kythe/cxx/indexer/cxx/_objs/semantic_hash/kythe/cxx/indexer/cxx/semantic_hash.o:kythe/cxx/indexer/cxx/semantic_hash.cc:function
kythe::SemanticHash::Hash(clang::TemplateArgument const&) const: error:
undefined reference to 'clang::QualType::getAsString[abi:cxx11]() const'
bazel-out/host/bin/kythe/cxx/indexer/cxx/_objs/semantic_hash/kythe/cxx/indexer/cxx/semantic_hash.o:kythe/cxx/indexer/cxx/semantic_hash.cc:function
kythe::SemanticHash::Hash(clang::TemplateArgument const&) const: error:
undefined reference to 'llvm::APInt::toString[abi:cxx11](unsigned int,
bool) const'
bazel-out/host/bin/kythe/cxx/indexer/cxx/_objs/semantic_hash/kythe/cxx/indexer/cxx/semantic_hash.o:kythe/cxx/indexer/cxx/semantic_hash.cc:function
kythe::SemanticHash::Hash(clang::QualType const&) const: error: undefined
reference to 'clang::QualType::getAsString[abi:cxx11]() const'
bazel-out/host/bin/kythe/cxx/indexer/cxx/_objs/semantic_hash/kythe/cxx/indexer/cxx/semantic_hash.o:kythe/cxx/indexer/cxx/semantic_hash.cc:function
kythe::SemanticHash::Hash(clang::RecordDecl const*) const: error: undefined
reference to 'clang::QualType::getAsString[abi:cxx11]() const'
bazel-out/host/bin/kythe/cxx/indexer/cxx/_objs/semantic_hash/kythe/cxx/indexer/cxx/semantic_hash.o:kythe/cxx/indexer/cxx/semantic_hash.cc:function
kythe::SemanticHash::Hash(clang::Selector const&) const: error: undefined
reference to 'clang::Selector::getAsString[abi:cxx11]() const'
bazel-out/host/bin/kythe/cxx/indexer/cxx/_objs/vfs/kythe/cxx/indexer/cxx/KytheVFS.o:kythe/cxx/indexer/cxx/KytheVFS.cc:function
kythe::IndexVFS::status(llvm::Twine const&): error: undefined reference to
'llvm::Twine::str[abi:cxx11]() const'
bazel-out/host/bin/kythe/cxx/indexer/cxx/_objs/vfs/kythe/cxx/indexer/cxx/KytheVFS.o:kythe/cxx/indexer/cxx/KytheVFS.cc:function
kythe::IndexVFS::openFileForRead(llvm::Twine const&): error: undefined
reference to 'llvm::Twine::str[abi:cxx11]() const'
bazel-out/host/bin/kythe/cxx/indexer/cxx/_objs/vfs/kythe/cxx/indexer/cxx/KytheVFS.o:kythe/cxx/indexer/cxx/KytheVFS.cc:function
kythe::IndexVFS::FileRecordForPathRoot(llvm::Twine const&, bool): error:
undefined reference to 'llvm::Twine::str[abi:cxx11]() const'
bazel-out/host/bin/kythe/cxx/indexer/cxx/_objs/vfs/kythe/cxx/indexer/cxx/KytheVFS.o:kythe/cxx/indexer/cxx/KytheVFS.cc:function
kythe::IndexVFS::setCurrentWorkingDirectory(llvm::Twine const&): error:
undefined reference to 'llvm::Twine::str[abi:cxx11]() const'
bazel-out/host/bin/kythe/cxx/common/_objs/lib/kythe/cxx/common/path_utils.o:kythe/cxx/common/path_utils.cc:function
kythe::RelativizePath(std::__cxx11::basic_string<char,
std::char_traits<char>, std::allocator<char> > const&,
std::__cxx11::basic_string<char, std::char_traits<char>,
std::allocator<char> > const&): error: undefined reference to
'clang::tooling::getAbsolutePath[abi:cxx11](llvm::StringRef)'
bazel-out/host/bin/kythe/cxx/common/_objs/lib/kythe/cxx/common/path_utils.o:kythe/cxx/common/path_utils.cc:function
kythe::RelativizePath(std::__cxx11::basic_string<char,
std::char_traits<char>, std::allocator<char> > const&,
std::__cxx11::basic_string<char, std::char_traits<char>,
std::allocator<char> > const&): error: undefined reference to
'clang::tooling::getAbsolutePath[abi:cxx11](llvm::StringRef)'
clang: error: linker command failed with exit code 1 (use -v to see
invocation)

**Comment by shahms** [comment]
LLVM needs to be re-built with the same version

**Comment by creachadair** [comment]
> LLVM needs to be re-built with the same version

Specifically, I think that you'll need to

    rm third_party/llvm/llvm/build
    ./tools/modules/update.sh

…after switching a compiler version.

**Comment by kamahen** [comment]
Hmmm ... I think I did do tools/modules/update.sh but for whatever reason
it didn't rebuild llvm.

Shouldn't bazel clean --expunge reset everything anyway (plus bazel build
@local_config_cc//:toolchain)?

**Comment by creachadair** [comment]
Aha, I see, it's not enough to remove the symlink, but one must remove the whole directory:

    rm -r third_party/llvm/llvm/build.*.*

As you say, though, starting from a fresh repo will also do the trick.

**Comment by creachadair** [comment]
I don't think we can prevent the errors from clang-3.5, so I think a documentation fix will have to do.
