### ISSUE TITLE
//kythe/go/platform/tools/kindex_file_generator:kindex_file_generator_test FAILED

### ISSUE THREAD

**Issue by kamahen** [google/kythe#2875]
The fix seems to be (change `du -k` to `du -b`:

```
--- a/kythe/go/platform/tools/kindex_file_generator/BUILD
+++ b/kythe/go/platform/tools/kindex_file_generator/BUILD
@@ -26,7 +26,7 @@ shell_tool_test(
       --output "$$kindex_output" \\
       --source "$$input"

-    size="$$(du -k "$$kindex_output" | cut -f1)"
+    size="$$(du -b "$$kindex_output" | cut -f1)"
     if [[ "$$size" -eq 0 ]] ; then
        echo "FAILED: output $$kindex_output is empty"
        exit 1
```

**Comment by zrlk** [comment]
I can't reproduce this problem. Maybe it's got something to do with LSW? That being said, I don't see any reason why we need to measure 1K blocks instead of bytes.

**Comment by kamahen** [comment]
I couldn't find any other instances of `du -k` (in fact, this was the only instance of `du`).

Personally, I would use  `wc -c`, but it's all a matter of taste. (And there are a number of instances of `wc -l` in the codebase).

**Comment by kamahen** [comment]
As for repro-ing this; I'm using the Linux subsystem under Windows, so it might behave slightly differently than regular Linux. Or perhaps I have a different version of `du` installed -- mine is from the `coreutils` package.

**Comment by zrlk** [comment]
What happens when you `touch foo ; du -k foo`?

**Comment by kamahen** [comment]
```
$ echo foo >/tmp/1; du -k /tmp/1 ; wc -c /tmp/1
0       /tmp/1
4 /tmp/1
```

```
$ touch /tmp/1; du -k /tmp/1
0       /tmp/1
```

BTW, you can avoid the `cut` by doing this:

```
$ echo foobar > /tmp/1; wc -c </tmp/1
```
