### ISSUE TITLE
Buildbots periodically "disappear" (report HTTP 502)

### ISSUE THREAD

**Issue by creachadair** [google/kythe#2878]
On several occasions in the past day or so, I've seen the following bad behaviour from the buildbots:

1. Create a pull request.
2. The buildbots start to run.
3. After a while, the buildbot detail pages start failing reporting 502.
4. Eventually, they come back.

I suspect we might need to provision bigger instances or something.

**Comment by creachadair** [comment]
After some investigation, I found a couple problems that I was able to work around, but may be fixable in a more complete way:

1. The VM was running an obsolete instance config (I recreated the instance group manually, and it picked up the newer version).

2. The existing buildbot jobs were stuck in an "acquiring lock" state. Manually instructing them to rebuild got them moving again.

I'm not sure whether either of these is the right fix, but at least we have builders again.

**Comment by schroederc** [comment]
This is very likely due to constrained resources and Bazel being a resource vacuum.  I've bumped up our requirements by quite a bit.
