### ISSUE TITLE
Migrate `tools/bazelrc` to `.bazelrc`

### ISSUE THREAD

**Issue by schroederc** [google/kythe#2897]
https://github.com/bazelbuild/bazel/commit/ec83598 is going to break our reliance on `%workspace%/tools/bazel.rc` and we must migrate to `%workspace%/.bazelrc`.  This will, however, break any users currently relying on their own `$HOME/.bazelrc` configuration until they migrate to the Bazel release containing that commit.

See https://github.com/bazelbuild/bazel/issues/4502 and https://github.com/bazelbuild/bazel/issues/5756 for more details.

**Comment by cvcal** [comment]
That's a good point - users who notice this could use `--bazelrc=~/.bazelrc` to keep the existing list, but it might be hard to let people know about this. If you're concerned, consider adding the option `--unconditional_warning="~/.bazelrc may not be being read, consider passing it through the --bazelrc flag." in the old file location, which won't be loaded for the new Bazel users.
