### ISSUE TITLE
Do maven preprocessing in golang, not a java jar

### ISSUE THREAD

**Issue by danielmoy-google** [google/kythe#2905]
For now the java xml library we're using works pretty well.

However it does require an additional os.exec - it'd be nice to do this preprocessing in golang native, since that's what we appear to be settled on for most of the execution.

**Comment by danielmoy-google** [comment]
https://github.com/beevik/etree maybe?

**Comment by creachadair** [comment]
https://github.com/subchen/go-xmldom is another option too.
