### ISSUE TITLE
asciidoc not in PATH on macOS

### ISSUE THREAD

**Issue by salguarnieri** [google/kythe#2955]
For example, you cannot build `//kythe/docs:modeling-libraries` because bazel cannot find asciidoc since it only looks in /bin and /usr/bin and brew installs asciidoc in /usr/local/bin/asciidoc.

This prevents you from running `bazel build ...`

**Comment by bzz** [comment]
Same happens with `bazel test //kythe/extractors/cmake:compilation_database` and GNU parallel installed from brew in `/usr/local/bin/parallel`.

**Comment by shahms** [comment]
We should probably define and use Bazel toolchains for the system tools we require...
