### ISSUE TITLE
os.Rename inside docker sometimes causes problems

### ISSUE THREAD

**Issue by danielmoy-google** [google/kythe#3051]
Specifically when backing up and restoring a repo build file (pom.xml, gradle.build, etc), the call to kythe/go/extractors/config/runextractor/backup Restore() calls os.Rename, which will sometimes trip this error:

"invalid cross-device link"

os.Rename doesn't play well with the different volumes in docker.

Potential fixes or workarounds:

* stick head in sand because the cases in which it fails (inside docker) are cases where we kind of don't care about build config backup restoring correctly, because once the image is done it disappears anyways
* use some other renaming thing like jenkins-x/jx/pkg/util.RenameFile
* similar to first option, but with less error spam - shim in yet-another-flag to disable backup/restore when inside docker
* ?? Probably there's more options I'm not thinking of right now.

**Comment by creachadair** [comment]
One workaround for this is to shell out to `mv`, which converts moves across filesystem boundaries into `cp` + `unlink`. It's no longer atomic, but in this case we're not relying on atomicity.

**Comment by creachadair** [comment]
(the above may be what the `RenameFile` util you mentioned already does)

**Comment by danielmoy-google** [comment]
Stick head in sand option is bad, specifically because we return error state on failed backup restore.  So if we really want to ignore it, would have to do third option there.

I like the idea of mv, I haven't actually looked at `RenameFile` yet to see what it does.

**Comment by danielmoy-google** [comment]
Well it doesn't just shell `mv`:

https://github.com/jenkins-x/jx/blob/master/pkg/util/files.go#L157

So that's nice at least.

**Comment by danielmoy-google** [comment]
I'm unclear if that dependency is worth it for just the one command though.

**Comment by creachadair** [comment]
> I'm unclear if that dependency is worth it for just the one command though.

Yeah, I am inclined to feel the same. On the other hand, copy+unlink has its own set of concerns to worry about. Can we work around this by always creating backups in a subdirectory of the original ? That should avoid most of the filesystem-boundary issues. (We might have to be careful about walking the filesystem in that case, but I think that's not too bad)

**Comment by danielmoy-google** [comment]
> always creating backups in a subdirectory of the original

This might be the best choice.  I'll mull this over a bit more.

**Comment by danielmoy-google** [comment]
This is what I missed:

https://golang.org/pkg/io/ioutil/#TempFile
> If dir is the empty string, TempFile uses the default directory for temporary files (see os.TempDir)

Because we're already in the relative directory and just calling this on `pom.xml`, ioutil.TempFile helpfully says "well clearly you meant `/tmp/pom.xml`".
