### ISSUE TITLE
C++ kzip writer does not generate a root directory

### ISSUE THREAD

**Issue by creachadair** [google/kythe#3054]
Per http://www.kythe.io/docs/kythe-kzip.html, a kzip file is intended to have a directory as its first entry. The C++ writer emits the correct subdirectory structure, but does not include the root directory itself.

**Comment by creachadair** [comment]
"A directory" in this case just means "an empty file whose name ends with `/`".

**Comment by shahms** [comment]
:-\ to that requirement as it seems like it would preclude using the standard `zip` tool to create an archive from an otherwise correctly structured directory
